<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/StrataAI.Domain/StrataAI.Domain.csproj" />
    <ProjectReference Include="../../src/StrataAI.Application/StrataAI.Application.csproj" />
    <ProjectReference Include="../../src/StrataAI.Infrastructure/StrataAI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
