import { expect, test } from '@playwright/test';

test('ARCH-11-TC-17 / PRD-02-TC-01/08: authenticated profile persistence and two-browser conflict recovery', async ({ page, context }) => {
  const email = `browser-${Date.now()}@example.test`;
  const password = 'browser-correct-horse-battery';
  await page.goto('/login');
  await page.getByRole('tab', { name: 'Register', exact: true }).click();
  await page.getByLabel(/^Display name/).fill('Browser Council');
  await page.getByLabel(/^Email/).fill(email);
  await page.getByLabel(/^Password/).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  await page.getByLabel(/^Password/).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/app\/demo\/boards\/demo-board$/);
  await page.getByRole('link', { name: 'Open profile' }).click();
  await expect(page.getByLabel(/^Display name/)).toHaveValue('Browser Council');
  const second = await context.newPage();
  await second.goto('/app/demo/profile');
  await expect(second.getByLabel(/^Display name/)).toHaveValue('Browser Council');
  await page.getByLabel(/^Display name/).fill('First browser save');
  await page.getByLabel(/^Timezone/).fill('UTC');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Profile saved.');
  await second.getByLabel(/^Display name/).fill('Stale browser save');
  await second.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(second.getByRole('alert')).toContainText('changed elsewhere');
  await expect(second.getByLabel(/^Display name/)).toHaveValue('Stale browser save');
  await expect(second.getByRole('button', { name: 'Save profile', exact: true })).toBeDisabled();
  await second.getByRole('button', { name: 'Discard edits and load latest profile' }).click();
  await expect(second.getByLabel(/^Display name/)).toHaveValue('First browser save');
  await expect(second.getByLabel(/^Timezone/)).toHaveValue('UTC');
  await second.getByLabel(/^Display name/).fill('Merged browser save');
  await second.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(second.getByRole('status')).toHaveText('Profile saved.');
  await page.reload();
  await expect(page.getByLabel(/^Display name/)).toHaveValue('Merged browser save');
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await second.reload();
  await expect(second).toHaveURL(/\/login$/);
});
