import { expect, test } from './releaseTest';
import { trackBoardReads } from './boardReadTracker';

for (const viewport of [{ width: 1280, height: 800 }, { width: 390, height: 844 }]) {
  test(`PRD-06: keyboard list positioning persists at ${viewport.width}px`, async ({ page, context }) => {
    await page.setViewportSize(viewport);
    const headers = { 'X-StrataAI-Request': '1' };
    const account = { email: `list-position-${viewport.width}-${Date.now()}@example.test`, password: 'list-position-correct-horse', displayName: 'List mover' };
    expect((await context.request.post('/auth/register', { headers, data: account })).status()).toBe(201);
    expect((await context.request.post('/auth/login', { headers, data: account })).status()).toBe(200);
    const createdOrg = await context.request.post('/organizations', { headers, data: { name: 'List positions' } });
    expect(createdOrg.status()).toBe(201); const org = (await createdOrg.json()).organization.id;
    const createdBoard = await context.request.post('/boards', { headers, data: { organizationId: org, name: 'Ordered lists', visibility: 'PRIVATE' } });
    expect(createdBoard.status()).toBe(201); const board = (await createdBoard.json()).id;
    const lists: { id: string; name: string; rank: string }[] = [];
    for (const name of ['First', 'Second']) {
      const result = await context.request.post(`/boards/${board}/lists`, { headers, data: { name } });
      expect(result.status()).toBe(201); lists.push(await result.json());
    }
    const reads = trackBoardReads(page, board, `/app/${org}/boards/${board}`);
    await page.goto(`/app/${org}/boards/${board}`); await expect.poll(reads).toBeGreaterThanOrEqual(2);
    const move = page.getByRole('button', { name: 'Move Second list', exact: true });
    await expect(move).toBeEnabled(); await move.focus(); await page.keyboard.press('Enter');
    const position = page.getByRole('combobox', { name: 'Position for Second' }); await position.press('ArrowDown');
    await expect(page.getByRole('listbox', { name: 'Position for Second' })).toBeVisible();
    await page.getByRole('option', { name: 'Before First', exact: true }).focus(); await page.keyboard.press('Enter');
    await page.getByRole('button', { name: 'Confirm list move', exact: true }).focus(); await page.keyboard.press('Enter');
    await expect(page.getByText('List move acknowledged. Current ordering is being checked.')).toBeVisible();
    await expect(move).toBeEnabled();
    await expect(move).toBeFocused();
    const result = await context.request.get(`/boards/${board}`); expect(result.status()).toBe(200);
    const order = (await result.json()).lists.map((column: { list: { id: string; rank: string; version: number } }) => column.list);
    expect(order.map((list: { id: string }) => list.id)).toEqual([lists[1].id, lists[0].id]);
    expect(order[0].version).toBe(2); expect(order[1].rank).toBe(lists[0].rank);
    if (viewport.width === 1280) {
      let outsideWrites = 0;
      page.on('request', request => { if (request.method() === 'PATCH' && /\/lists\/[^/]+$/.test(new URL(request.url()).pathname)) outsideWrites++; });
      const outsideSource = await page.getByRole('button', { name: 'Drag First list', exact: true }).boundingBox();
      const outsideTarget = await page.getByRole('heading', { name: 'Ordered lists', exact: true }).boundingBox();
      expect(outsideSource).not.toBeNull(); expect(outsideTarget).not.toBeNull();
      await page.mouse.move(outsideSource!.x + outsideSource!.width / 2, outsideSource!.y + outsideSource!.height / 2); await page.mouse.down();
      await page.mouse.move(outsideTarget!.x + outsideTarget!.width / 2, outsideTarget!.y + outsideTarget!.height / 2, { steps: 12 }); await page.mouse.up();
      expect(outsideWrites).toBe(0);
      const afterOutside = await context.request.get(`/boards/${board}`); expect(afterOutside.status()).toBe(200);
      expect((await afterOutside.json()).lists.map((column: { list: unknown }) => column.list)).toEqual(order);
      const source = await page.getByRole('button', { name: 'Drag First list', exact: true }).boundingBox();
      const target = await page.getByRole('region', { name: 'Second', exact: true }).boundingBox();
      expect(source).not.toBeNull(); expect(target).not.toBeNull();
      await page.mouse.move(source!.x + source!.width / 2, source!.y + source!.height / 2);
      await page.mouse.down();
      await page.mouse.move(target!.x + target!.width / 2, target!.y + target!.height / 2, { steps: 12 });
      await page.mouse.up();
      await expect(page.getByRole('region').first()).toHaveAccessibleName('First');
      await expect(page.getByRole('button', { name: 'Move First list', exact: true })).toBeEnabled();
      const current = await context.request.get(`/boards/${board}`); expect(current.status()).toBe(200);
      const persisted = (await current.json()).lists.map((column: { list: { id: string; version: number } }) => column.list);
      expect(persisted.map((list: { id: string }) => list.id)).toEqual([lists[0].id, lists[1].id]);
      expect(persisted.map((list: { version: number }) => list.version)).toEqual([2, 2]);
    }
    const keyboardName = viewport.width === 1280 ? 'Second' : 'First';
    const dragHandle = page.getByRole('button', { name: `Drag ${keyboardName} list`, exact: true });
    const beforeKeyboard = await (await context.request.get(`/boards/${board}`)).json();
    const targetAnnouncement = `${keyboardName} list can be dropped before ${beforeKeyboard.lists[0].list.name}.`;
    let moveWrites = 0;
    page.on('request', request => { if (request.method() === 'PATCH' && request.url().includes('/lists/')) moveWrites++; });
    await dragHandle.focus(); await page.keyboard.press('Space');
    await expect(page.getByText(`Dragging ${keyboardName} list. Use Left and Right to choose a position.`, { exact: true })).toBeAttached();
    await page.keyboard.press('ArrowLeft');
    await expect(page.getByText(targetAnnouncement, { exact: true })).toBeAttached();
    await page.keyboard.press('Escape');
    await expect(page.getByText(`Drag cancelled. ${keyboardName} list was not moved.`, { exact: true })).toBeAttached();
    await expect(dragHandle).not.toHaveAttribute('aria-pressed', 'true');
    expect(moveWrites).toBe(0);
    expect((await (await context.request.get(`/boards/${board}`)).json()).lists).toEqual(beforeKeyboard.lists);
    await dragHandle.focus(); await page.keyboard.press('Space');
    await expect(dragHandle).toHaveAttribute('aria-pressed', 'true');
    await page.keyboard.press('ArrowLeft');
    await expect(page.getByText(targetAnnouncement, { exact: true })).toBeAttached();
    await page.keyboard.press('Space');
    await expect(page.getByRole('region').first()).toHaveAccessibleName(keyboardName);
    await expect(page.getByRole('button', { name: `Move ${keyboardName} list`, exact: true })).toBeEnabled();
    expect(moveWrites).toBe(1);
    const afterKeyboard = await (await context.request.get(`/boards/${board}`)).json();
    expect(afterKeyboard.lists[0].list.id).toBe(lists[viewport.width === 1280 ? 1 : 0].id);
    expect(afterKeyboard.lists[0].list.version).toBe(beforeKeyboard.lists[1].list.version + 1);
    expect(afterKeyboard.lists[1].list.rank).toBe(beforeKeyboard.lists[0].list.rank);
    await page.reload();
    await expect(page.getByRole('region').first()).toHaveAccessibleName(keyboardName);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  });
}
