<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../StrataAI.Application/StrataAI.Application.csproj" />
    <ProjectReference Include="../StrataAI.Domain/StrataAI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
